export enum NI_PLAYER_EVENT {
    BEFORE_INIT = 'before_init',
    MOUNTED = 'mounted',
    VIDEO_QUALITY_CHANGING = 'video_quality_changing',
    VIDEO_QUALITY_CHANGED = 'video_quality_changed',
    VIDEO_CAN_PLAY = 'video_can_play',
    VIDEO_SEEKED = 'video_seeked',
    VIDEO_PLAYRATE_CHANGED = 'video_playrate_changed',
    VIDEO_PLAY = 'video_play',
    VIDEO_PAUSE = 'video_pause',
    VIDEO_VOLUME_CHANGED = 'video_volume_changed',
    VIDEO_WAITING = 'video_waiting',
    VIDEO_PLAYING = 'video_playing',
    VIDEO_DURATION_CHANGED = 'video_duration_changed',
    VIDEO_TIME_UPDATE = 'video_time_update',
    VIDEO_ENDED = 'video_ended',
    VIDEO_ERROR = 'video_error',
    VIDEO_LOADING = 'video_loading',
}